spring:
  application:
    name: ToDoListOnSpring
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_todo?currentSchema=todo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: SpringTodoPool
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 600000

# Добавленные настройки для работы со статическими ресурсами
  web:
    resources:
      add-mappings: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: todo

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs  # Путь для JSON-документации
  swagger-ui:
    enabled: true
    path: /swagger-ui.html  # Путь к Swagger UI
    tags-sorter: alpha  # Сортировка тегов по алфавиту
    operations-sorter: alpha  # Сортировка операций по алфавиту